#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $BRANCH = 'gh-pages' ]]
then
    echo "Running build"
    yarn build
    git add build
    git add _data

    yarn validate-json
else
    echo 'Skipping build'
fi
